# Generated by Django 4.2.5 on 2023-09-20 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="posted_date", new_name="data_added",
        ),
    ]
